# Las heurísticas se refieren al camino más corto entre los nodos, que corresponde a trazar una línea recta
# Se definen de la siguiente forma
heuristicas = {'Recepción': {'Recepción': 0,
                             'Sala de espera': 5,
                             'Sala de espera B': 11.18,
                             'Pasillo sección A': 14.14,
                             'Pasillo sección B': 18.03,
                             'Pasillo sección C': 22.36,
                             'Pasillo de almacén': 5,
                             'Almacén': 11.18,
                             'Sala de examen 1': 15.81,
                             'Rehabilitación B': 15,
                             'Sala de examen 2': 15.81,
                             'Rehabilitación': 20,
                             'Oficina': 21.21,
                             'Acceso a azotea': 15.81},
               'Sala de espera': {'Recepción': 5,
                                  'Sala de espera': 0,
                                  'Sala de espera B': 10,
                                  'Pasillo sección A': 11.18,
                                  'Pasillo sección B': 14.14,
                                  'Pasillo sección C': 18.03,
                                  'Pasillo de almacén': 7.07,
                                  'Almacén': 7.07,
                                  'Sala de examen 1': 11.18,
                                  'Rehabilitación B': 10,
                                  'Sala de examen 2': 11.18,
                                  'Rehabilitación': 15,
                                  'Oficina': 18.03,
                                  'Acceso a azotea': 15},
               'Sala de espera B': {'Recepción': 11.18,
                                    'Sala de espera': 10,
                                    'Sala de espera B': 0,
                                    'Pasillo sección A': 5,
                                    'Pasillo sección B': 10,
                                    'Pasillo sección C': 15,
                                    'Pasillo de almacén': 15.81,
                                    'Almacén': 15.81,
                                    'Sala de examen 1': 18.03,
                                    'Rehabilitación B': 14.14,
                                    'Sala de examen 2': 11.18,
                                    'Rehabilitación': 18.03,
                                    'Oficina': 11.18,
                                    'Acceso a azotea': 5},
               'Pasillo sección A': {'Recepción': 14.14,
                                     'Sala de espera': 11.18,
                                     'Sala de espera B': 5,
                                     'Pasillo sección A': 0,
                                     'Pasillo sección B': 5,
                                     'Pasillo sección C': 10,
                                     'Pasillo de almacén': 18.03,
                                     'Almacén': 15,
                                     'Sala de examen 1': 15.81,
                                     'Rehabilitación B': 11.18,
                                     'Sala de examen 2': 7.07,
                                     'Rehabilitación': 14.14,
                                     'Oficina': 7.07,
                                     'Acceso a azotea': 7.07},
               'Pasillo sección B': {'Recepción': 18.03,
                                     'Sala de espera': 14.14,
                                     'Sala de espera B': 10,
                                     'Pasillo sección A': 5,
                                     'Pasillo sección B': 0,
                                     'Pasillo sección C': 5,
                                     'Pasillo de almacén': 21.21,
                                     'Almacén': 15.81,
                                     'Sala de examen 1': 15,
                                     'Rehabilitación B': 10,
                                     'Sala de examen 2': 5,
                                     'Rehabilitación': 11.18,
                                     'Oficina': 5,
                                     'Acceso a azotea': 11.18},
               'Pasillo sección C': {'Recepción': 22.36,
                                     'Sala de espera': 18.03,
                                     'Sala de espera B': 15,
                                     'Pasillo sección A': 10,
                                     'Pasillo sección B': 5,
                                     'Pasillo sección C': 0,
                                     'Pasillo de almacén': 25,
                                     'Almacén': 18.03,
                                     'Sala de examen 1': 15.81,
                                     'Rehabilitación B': 11.18,
                                     'Sala de examen 2': 7.07,
                                     'Rehabilitación': 5,
                                     'Oficina': 7.07,
                                     'Acceso a azotea': 15.81},
               'Pasillo de almacén': {'Recepción': 5,
                                      'Sala de espera': 7.07,
                                      'Sala de espera B': 15.81,
                                      'Pasillo sección A': 18.03,
                                      'Pasillo sección B': 21.21,
                                      'Pasillo sección C': 25,
                                      'Pasillo de almacén': 0,
                                      'Almacén': 10,
                                      'Sala de examen 1': 15,
                                      'Rehabilitación B': 15.81,
                                      'Sala de examen 2': 18.03,
                                      'Rehabilitación': 20.62,
                                      'Oficina': 25,
                                      'Acceso a azotea': 20.62},
               'Almacén': {'Recepción': 11.18,
                           'Sala de espera': 7.07,
                           'Sala de espera B': 15.81,
                           'Pasillo sección A': 15,
                           'Pasillo sección B': 15.81,
                           'Pasillo sección C': 18.03,
                           'Pasillo de almacén': 10,
                           'Almacén': 0,
                           'Sala de examen 1': 5,
                           'Rehabilitación B': 7.07,
                           'Sala de examen 2': 11.18,
                           'Rehabilitación': 11.18,
                           'Oficina': 22.36,
                           'Acceso a azotea': 20.62},
               'Sala de examen 1': {'Recepción': 15.81,
                                    'Sala de espera': 11.18,
                                    'Sala de espera B': 18.03,
                                    'Pasillo sección A': 15.81,
                                    'Pasillo sección B': 15,
                                    'Pasillo sección C': 15.81,
                                    'Pasillo de almacén': 15,
                                    'Almacén': 5,
                                    'Sala de examen 1': 0,
                                    'Rehabilitación B': 5,
                                    'Sala de examen 2': 10,
                                    'Rehabilitación': 7.07,
                                    'Oficina': 20,
                                    'Acceso a azotea': 22.36},
               'Rehabilitación B': {'Recepción': 15,
                                    'Sala de espera': 10,
                                    'Sala de espera B': 14.14,
                                    'Pasillo sección A': 11.18,
                                    'Pasillo sección B': 10,
                                    'Pasillo sección C': 11.18,
                                    'Pasillo de almacén': 15.81,
                                    'Almacén': 7.07,
                                    'Sala de examen 1': 5,
                                    'Rehabilitación B': 0,
                                    'Sala de examen 2': 5,
                                    'Rehabilitación': 5,
                                    'Oficina': 15,
                                    'Acceso a azotea': 18.03},
               'Sala de examen 2': {'Recepción': 15.81,
                                    'Sala de espera': 11.18,
                                    'Sala de espera B': 11.18,
                                    'Pasillo sección A': 7.07,
                                    'Pasillo sección B': 5,
                                    'Pasillo sección C': 7.07,
                                    'Pasillo de almacén': 18.03,
                                    'Almacén': 11.18,
                                    'Sala de examen 1': 10,
                                    'Rehabilitación B': 5,
                                    'Sala de examen 2': 0,
                                    'Rehabilitación': 7.07,
                                    'Oficina': 10,
                                    'Acceso a azotea': 14.14},
               'Rehabilitación': {'Recepción': 20,
                                  'Sala de espera': 15,
                                  'Sala de espera B': 18.03,
                                  'Pasillo sección A': 14.14,
                                  'Pasillo sección B': 11.18,
                                  'Pasillo sección C': 5,
                                  'Pasillo de almacén': 20.62,
                                  'Almacén': 11.18,
                                  'Sala de examen 1': 7.07,
                                  'Rehabilitación B': 5,
                                  'Sala de examen 2': 7.07,
                                  'Rehabilitación': 0,
                                  'Oficina': 7.07,
                                  'Acceso a azotea': 18.03},
               'Oficina': {'Recepción': 21.21,
                           'Sala de espera': 18.03,
                           'Sala de espera B': 11.18,
                           'Pasillo sección A': 7.07,
                           'Pasillo sección B': 5,
                           'Pasillo sección C': 7.07,
                           'Pasillo de almacén': 25,
                           'Almacén': 22.36,
                           'Sala de examen 1': 20,
                           'Rehabilitación B': 15,
                           'Sala de examen 2': 10,
                           'Rehabilitación': 7.07,
                           'Oficina': 0,
                           'Acceso a azotea': 10},
               'Acceso a azotea': {'Recepción': 15.81,
                                   'Sala de espera': 15,
                                   'Sala de espera B': 5,
                                   'Pasillo sección A': 7.07,
                                   'Pasillo sección B': 11.18,
                                   'Pasillo sección C': 15.81,
                                   'Pasillo de almacén': 20.62,
                                   'Almacén': 20.62,
                                   'Sala de examen 1': 22.36,
                                   'Rehabilitación B': 18.03,
                                   'Sala de examen 2': 14.14,
                                   'Rehabilitación': 18.03,
                                   'Oficina': 7.07,
                                   'Acceso a azotea': 0}}
